"""empty message

Revision ID: 916187b6841e
Revises: 
Create Date: 2020-04-20 22:10:38.984706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916187b6841e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('rotation', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'rotation')
    # ### end Alembic commands ###
