"""empty message

Revision ID: 9aeb7bfad704
Revises: 916187b6841e
Create Date: 2020-04-21 10:08:47.729681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aeb7bfad704'
down_revision = '916187b6841e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bins', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('bins', sa.Column('position', sa.Integer(), nullable=True))
    op.alter_column('stations', 'rotation',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stations', 'rotation',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('bins', 'position')
    op.drop_column('bins', 'name')
    # ### end Alembic commands ###
